/**:
  ros__parameters:
    res: 0.05
    width: 50 #60
    height: 60 #60
    origin_x: 0.0
    origin_y: -1.5 #- (self.height * self.res) / 2.0
    dx: -0.34
    dy: 0.0
    closing_kernel_size: 1

