int64 idx
int64 xi
int64 yi
int64 xf
int64 yf
float64 alpha
float64 alpha1
float64 beta
float64 weight
float64 weight1
float64 weight2
float64 margin
bool return_path
bool return_expanded
bool return_gvalue
bool return_heuristic
bool save_path
string path_folder
string map_file
int64 edge_type
int64[] custom_data_int
float64[] custom_data_double
int64[] additional_obstacles
---
float64 cost
float64 cost2
int64 expansion
float64 time_pre
float64 time_plan
int64[] path_x
int64[] path_y
int64[] expanded_x
int64[] expanded_y
float64[] g
float64[] h
bool find
int64[] custom_data_int
float64[] custom_data_double
