/**:
  ros__parameters:
    joy_msg: ""
    cmd_msg: "/fake_cmd"
    scan_msg: ""
    grid_msg: "/bev/occupancy_grid"
    max_linear_vel : 0.5
    max_side_vel : 0.2
    max_angular_vel : 45.0
    acc: 1.0
    dt: 0.1
    #
    collision_radius: 0.3
    collision_margin: 0.1
    resolution_x: 4
    resolution_y: 2
    resolution_th: 4
